package com.ziumks.edugis.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CodeExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public CodeExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	protected CodeExample(CodeExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table PMS.CODE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andCodeIsNull() {
			addCriterion("CODE is null");
			return this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CODE is not null");
			return this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CODE =", value, "code");
			return this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CODE <>", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CODE >", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "code");
			return this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CODE <", value, "code");
			return this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "code");
			return this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CODE like", value, "code");
			return this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CODE not like", value, "code");
			return this;
		}

		public Criteria andCodeIn(List values) {
			addCriterion("CODE in", values, "code");
			return this;
		}

		public Criteria andCodeNotIn(List values) {
			addCriterion("CODE not in", values, "code");
			return this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "code");
			return this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "code");
			return this;
		}

		public Criteria andCodeIdIsNull() {
			addCriterion("CODE_ID is null");
			return this;
		}

		public Criteria andCodeIdIsNotNull() {
			addCriterion("CODE_ID is not null");
			return this;
		}

		public Criteria andCodeIdEqualTo(String value) {
			addCriterion("CODE_ID =", value, "codeId");
			return this;
		}

		public Criteria andCodeIdNotEqualTo(String value) {
			addCriterion("CODE_ID <>", value, "codeId");
			return this;
		}

		public Criteria andCodeIdGreaterThan(String value) {
			addCriterion("CODE_ID >", value, "codeId");
			return this;
		}

		public Criteria andCodeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_ID >=", value, "codeId");
			return this;
		}

		public Criteria andCodeIdLessThan(String value) {
			addCriterion("CODE_ID <", value, "codeId");
			return this;
		}

		public Criteria andCodeIdLessThanOrEqualTo(String value) {
			addCriterion("CODE_ID <=", value, "codeId");
			return this;
		}

		public Criteria andCodeIdLike(String value) {
			addCriterion("CODE_ID like", value, "codeId");
			return this;
		}

		public Criteria andCodeIdNotLike(String value) {
			addCriterion("CODE_ID not like", value, "codeId");
			return this;
		}

		public Criteria andCodeIdIn(List values) {
			addCriterion("CODE_ID in", values, "codeId");
			return this;
		}

		public Criteria andCodeIdNotIn(List values) {
			addCriterion("CODE_ID not in", values, "codeId");
			return this;
		}

		public Criteria andCodeIdBetween(String value1, String value2) {
			addCriterion("CODE_ID between", value1, value2, "codeId");
			return this;
		}

		public Criteria andCodeIdNotBetween(String value1, String value2) {
			addCriterion("CODE_ID not between", value1, value2, "codeId");
			return this;
		}

		public Criteria andCodeNameIsNull() {
			addCriterion("CODE_NAME is null");
			return this;
		}

		public Criteria andCodeNameIsNotNull() {
			addCriterion("CODE_NAME is not null");
			return this;
		}

		public Criteria andCodeNameEqualTo(String value) {
			addCriterion("CODE_NAME =", value, "codeName");
			return this;
		}

		public Criteria andCodeNameNotEqualTo(String value) {
			addCriterion("CODE_NAME <>", value, "codeName");
			return this;
		}

		public Criteria andCodeNameGreaterThan(String value) {
			addCriterion("CODE_NAME >", value, "codeName");
			return this;
		}

		public Criteria andCodeNameGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_NAME >=", value, "codeName");
			return this;
		}

		public Criteria andCodeNameLessThan(String value) {
			addCriterion("CODE_NAME <", value, "codeName");
			return this;
		}

		public Criteria andCodeNameLessThanOrEqualTo(String value) {
			addCriterion("CODE_NAME <=", value, "codeName");
			return this;
		}

		public Criteria andCodeNameLike(String value) {
			addCriterion("CODE_NAME like", value, "codeName");
			return this;
		}

		public Criteria andCodeNameNotLike(String value) {
			addCriterion("CODE_NAME not like", value, "codeName");
			return this;
		}

		public Criteria andCodeNameIn(List values) {
			addCriterion("CODE_NAME in", values, "codeName");
			return this;
		}

		public Criteria andCodeNameNotIn(List values) {
			addCriterion("CODE_NAME not in", values, "codeName");
			return this;
		}

		public Criteria andCodeNameBetween(String value1, String value2) {
			addCriterion("CODE_NAME between", value1, value2, "codeName");
			return this;
		}

		public Criteria andCodeNameNotBetween(String value1, String value2) {
			addCriterion("CODE_NAME not between", value1, value2, "codeName");
			return this;
		}

		public Criteria andCodeDescIsNull() {
			addCriterion("CODE_DESC is null");
			return this;
		}

		public Criteria andCodeDescIsNotNull() {
			addCriterion("CODE_DESC is not null");
			return this;
		}

		public Criteria andCodeDescEqualTo(String value) {
			addCriterion("CODE_DESC =", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescNotEqualTo(String value) {
			addCriterion("CODE_DESC <>", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescGreaterThan(String value) {
			addCriterion("CODE_DESC >", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_DESC >=", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescLessThan(String value) {
			addCriterion("CODE_DESC <", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescLessThanOrEqualTo(String value) {
			addCriterion("CODE_DESC <=", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescLike(String value) {
			addCriterion("CODE_DESC like", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescNotLike(String value) {
			addCriterion("CODE_DESC not like", value, "codeDesc");
			return this;
		}

		public Criteria andCodeDescIn(List values) {
			addCriterion("CODE_DESC in", values, "codeDesc");
			return this;
		}

		public Criteria andCodeDescNotIn(List values) {
			addCriterion("CODE_DESC not in", values, "codeDesc");
			return this;
		}

		public Criteria andCodeDescBetween(String value1, String value2) {
			addCriterion("CODE_DESC between", value1, value2, "codeDesc");
			return this;
		}

		public Criteria andCodeDescNotBetween(String value1, String value2) {
			addCriterion("CODE_DESC not between", value1, value2, "codeDesc");
			return this;
		}

		public Criteria andCodeIdNameIsNull() {
			addCriterion("CODE_ID_NAME is null");
			return this;
		}

		public Criteria andCodeIdNameIsNotNull() {
			addCriterion("CODE_ID_NAME is not null");
			return this;
		}

		public Criteria andCodeIdNameEqualTo(String value) {
			addCriterion("CODE_ID_NAME =", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameNotEqualTo(String value) {
			addCriterion("CODE_ID_NAME <>", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameGreaterThan(String value) {
			addCriterion("CODE_ID_NAME >", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_ID_NAME >=", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameLessThan(String value) {
			addCriterion("CODE_ID_NAME <", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameLessThanOrEqualTo(String value) {
			addCriterion("CODE_ID_NAME <=", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameLike(String value) {
			addCriterion("CODE_ID_NAME like", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameNotLike(String value) {
			addCriterion("CODE_ID_NAME not like", value, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameIn(List values) {
			addCriterion("CODE_ID_NAME in", values, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameNotIn(List values) {
			addCriterion("CODE_ID_NAME not in", values, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameBetween(String value1, String value2) {
			addCriterion("CODE_ID_NAME between", value1, value2, "codeIdName");
			return this;
		}

		public Criteria andCodeIdNameNotBetween(String value1, String value2) {
			addCriterion("CODE_ID_NAME not between", value1, value2, "codeIdName");
			return this;
		}

		public Criteria andCodeIdDescIsNull() {
			addCriterion("CODE_ID_DESC is null");
			return this;
		}

		public Criteria andCodeIdDescIsNotNull() {
			addCriterion("CODE_ID_DESC is not null");
			return this;
		}

		public Criteria andCodeIdDescEqualTo(String value) {
			addCriterion("CODE_ID_DESC =", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescNotEqualTo(String value) {
			addCriterion("CODE_ID_DESC <>", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescGreaterThan(String value) {
			addCriterion("CODE_ID_DESC >", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_ID_DESC >=", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescLessThan(String value) {
			addCriterion("CODE_ID_DESC <", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescLessThanOrEqualTo(String value) {
			addCriterion("CODE_ID_DESC <=", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescLike(String value) {
			addCriterion("CODE_ID_DESC like", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescNotLike(String value) {
			addCriterion("CODE_ID_DESC not like", value, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescIn(List values) {
			addCriterion("CODE_ID_DESC in", values, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescNotIn(List values) {
			addCriterion("CODE_ID_DESC not in", values, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescBetween(String value1, String value2) {
			addCriterion("CODE_ID_DESC between", value1, value2, "codeIdDesc");
			return this;
		}

		public Criteria andCodeIdDescNotBetween(String value1, String value2) {
			addCriterion("CODE_ID_DESC not between", value1, value2, "codeIdDesc");
			return this;
		}

		public Criteria andCodeGroupIsNull() {
			addCriterion("CODE_GROUP is null");
			return this;
		}

		public Criteria andCodeGroupIsNotNull() {
			addCriterion("CODE_GROUP is not null");
			return this;
		}

		public Criteria andCodeGroupEqualTo(String value) {
			addCriterion("CODE_GROUP =", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupNotEqualTo(String value) {
			addCriterion("CODE_GROUP <>", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupGreaterThan(String value) {
			addCriterion("CODE_GROUP >", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupGreaterThanOrEqualTo(String value) {
			addCriterion("CODE_GROUP >=", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupLessThan(String value) {
			addCriterion("CODE_GROUP <", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupLessThanOrEqualTo(String value) {
			addCriterion("CODE_GROUP <=", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupLike(String value) {
			addCriterion("CODE_GROUP like", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupNotLike(String value) {
			addCriterion("CODE_GROUP not like", value, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupIn(List values) {
			addCriterion("CODE_GROUP in", values, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupNotIn(List values) {
			addCriterion("CODE_GROUP not in", values, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupBetween(String value1, String value2) {
			addCriterion("CODE_GROUP between", value1, value2, "codeGroup");
			return this;
		}

		public Criteria andCodeGroupNotBetween(String value1, String value2) {
			addCriterion("CODE_GROUP not between", value1, value2, "codeGroup");
			return this;
		}

		public Criteria andUseYnIsNull() {
			addCriterion("USE_YN is null");
			return this;
		}

		public Criteria andUseYnIsNotNull() {
			addCriterion("USE_YN is not null");
			return this;
		}

		public Criteria andUseYnEqualTo(String value) {
			addCriterion("USE_YN =", value, "useYn");
			return this;
		}

		public Criteria andUseYnNotEqualTo(String value) {
			addCriterion("USE_YN <>", value, "useYn");
			return this;
		}

		public Criteria andUseYnGreaterThan(String value) {
			addCriterion("USE_YN >", value, "useYn");
			return this;
		}

		public Criteria andUseYnGreaterThanOrEqualTo(String value) {
			addCriterion("USE_YN >=", value, "useYn");
			return this;
		}

		public Criteria andUseYnLessThan(String value) {
			addCriterion("USE_YN <", value, "useYn");
			return this;
		}

		public Criteria andUseYnLessThanOrEqualTo(String value) {
			addCriterion("USE_YN <=", value, "useYn");
			return this;
		}

		public Criteria andUseYnLike(String value) {
			addCriterion("USE_YN like", value, "useYn");
			return this;
		}

		public Criteria andUseYnNotLike(String value) {
			addCriterion("USE_YN not like", value, "useYn");
			return this;
		}

		public Criteria andUseYnIn(List values) {
			addCriterion("USE_YN in", values, "useYn");
			return this;
		}

		public Criteria andUseYnNotIn(List values) {
			addCriterion("USE_YN not in", values, "useYn");
			return this;
		}

		public Criteria andUseYnBetween(String value1, String value2) {
			addCriterion("USE_YN between", value1, value2, "useYn");
			return this;
		}

		public Criteria andUseYnNotBetween(String value1, String value2) {
			addCriterion("USE_YN not between", value1, value2, "useYn");
			return this;
		}

		public Criteria andSortOrderIsNull() {
			addCriterion("SORT_ORDER is null");
			return this;
		}

		public Criteria andSortOrderIsNotNull() {
			addCriterion("SORT_ORDER is not null");
			return this;
		}

		public Criteria andSortOrderEqualTo(Integer value) {
			addCriterion("SORT_ORDER =", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderNotEqualTo(Integer value) {
			addCriterion("SORT_ORDER <>", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderGreaterThan(Integer value) {
			addCriterion("SORT_ORDER >", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER >=", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderLessThan(Integer value) {
			addCriterion("SORT_ORDER <", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderLessThanOrEqualTo(Integer value) {
			addCriterion("SORT_ORDER <=", value, "sortOrder");
			return this;
		}

		public Criteria andSortOrderIn(List values) {
			addCriterion("SORT_ORDER in", values, "sortOrder");
			return this;
		}

		public Criteria andSortOrderNotIn(List values) {
			addCriterion("SORT_ORDER not in", values, "sortOrder");
			return this;
		}

		public Criteria andSortOrderBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER between", value1, value2, "sortOrder");
			return this;
		}

		public Criteria andSortOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT_ORDER not between", value1, value2, "sortOrder");
			return this;
		}

		public Criteria andRegisterIdIsNull() {
			addCriterion("REGISTER_ID is null");
			return this;
		}

		public Criteria andRegisterIdIsNotNull() {
			addCriterion("REGISTER_ID is not null");
			return this;
		}

		public Criteria andRegisterIdEqualTo(String value) {
			addCriterion("REGISTER_ID =", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdNotEqualTo(String value) {
			addCriterion("REGISTER_ID <>", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdGreaterThan(String value) {
			addCriterion("REGISTER_ID >", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
			addCriterion("REGISTER_ID >=", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdLessThan(String value) {
			addCriterion("REGISTER_ID <", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdLessThanOrEqualTo(String value) {
			addCriterion("REGISTER_ID <=", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdLike(String value) {
			addCriterion("REGISTER_ID like", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdNotLike(String value) {
			addCriterion("REGISTER_ID not like", value, "registerId");
			return this;
		}

		public Criteria andRegisterIdIn(List values) {
			addCriterion("REGISTER_ID in", values, "registerId");
			return this;
		}

		public Criteria andRegisterIdNotIn(List values) {
			addCriterion("REGISTER_ID not in", values, "registerId");
			return this;
		}

		public Criteria andRegisterIdBetween(String value1, String value2) {
			addCriterion("REGISTER_ID between", value1, value2, "registerId");
			return this;
		}

		public Criteria andRegisterIdNotBetween(String value1, String value2) {
			addCriterion("REGISTER_ID not between", value1, value2, "registerId");
			return this;
		}

		public Criteria andRegisterDateIsNull() {
			addCriterion("REGISTER_DATE is null");
			return this;
		}

		public Criteria andRegisterDateIsNotNull() {
			addCriterion("REGISTER_DATE is not null");
			return this;
		}

		public Criteria andRegisterDateEqualTo(Date value) {
			addCriterion("REGISTER_DATE =", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateNotEqualTo(Date value) {
			addCriterion("REGISTER_DATE <>", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateGreaterThan(Date value) {
			addCriterion("REGISTER_DATE >", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateGreaterThanOrEqualTo(Date value) {
			addCriterion("REGISTER_DATE >=", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateLessThan(Date value) {
			addCriterion("REGISTER_DATE <", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateLessThanOrEqualTo(Date value) {
			addCriterion("REGISTER_DATE <=", value, "registerDate");
			return this;
		}

		public Criteria andRegisterDateIn(List values) {
			addCriterion("REGISTER_DATE in", values, "registerDate");
			return this;
		}

		public Criteria andRegisterDateNotIn(List values) {
			addCriterion("REGISTER_DATE not in", values, "registerDate");
			return this;
		}

		public Criteria andRegisterDateBetween(Date value1, Date value2) {
			addCriterion("REGISTER_DATE between", value1, value2, "registerDate");
			return this;
		}

		public Criteria andRegisterDateNotBetween(Date value1, Date value2) {
			addCriterion("REGISTER_DATE not between", value1, value2, "registerDate");
			return this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("UPDATE_ID is null");
			return this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("UPDATE_ID is not null");
			return this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("UPDATE_ID =", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("UPDATE_ID <>", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("UPDATE_ID >", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID >=", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("UPDATE_ID <", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_ID <=", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("UPDATE_ID like", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("UPDATE_ID not like", value, "updateId");
			return this;
		}

		public Criteria andUpdateIdIn(List values) {
			addCriterion("UPDATE_ID in", values, "updateId");
			return this;
		}

		public Criteria andUpdateIdNotIn(List values) {
			addCriterion("UPDATE_ID not in", values, "updateId");
			return this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("UPDATE_ID between", value1, value2, "updateId");
			return this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_ID not between", value1, value2, "updateId");
			return this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return this;
		}

		public Criteria andUpdateDateIn(List values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotIn(List values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return this;
		}
	}
}