package com.ziumks.edugis.dao;

import java.util.Date;

public class Code extends CodeKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.CODE_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String codeName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.CODE_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String codeDesc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.CODE_ID_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String codeIdName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.CODE_ID_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String codeIdDesc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.CODE_GROUP
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String codeGroup;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.USE_YN
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String useYn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.SORT_ORDER
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.REGISTER_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String registerId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.REGISTER_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private Date registerDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.UPDATE_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private String updateId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PMS.CODE.UPDATE_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	private Date updateDate;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.CODE_NAME
	 * @return  the value of PMS.CODE.CODE_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getCodeName() {
		return codeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.CODE_NAME
	 * @param codeName  the value for PMS.CODE.CODE_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.CODE_DESC
	 * @return  the value of PMS.CODE.CODE_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getCodeDesc() {
		return codeDesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.CODE_DESC
	 * @param codeDesc  the value for PMS.CODE.CODE_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.CODE_ID_NAME
	 * @return  the value of PMS.CODE.CODE_ID_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getCodeIdName() {
		return codeIdName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.CODE_ID_NAME
	 * @param codeIdName  the value for PMS.CODE.CODE_ID_NAME
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setCodeIdName(String codeIdName) {
		this.codeIdName = codeIdName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.CODE_ID_DESC
	 * @return  the value of PMS.CODE.CODE_ID_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getCodeIdDesc() {
		return codeIdDesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.CODE_ID_DESC
	 * @param codeIdDesc  the value for PMS.CODE.CODE_ID_DESC
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setCodeIdDesc(String codeIdDesc) {
		this.codeIdDesc = codeIdDesc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.CODE_GROUP
	 * @return  the value of PMS.CODE.CODE_GROUP
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getCodeGroup() {
		return codeGroup;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.CODE_GROUP
	 * @param codeGroup  the value for PMS.CODE.CODE_GROUP
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setCodeGroup(String codeGroup) {
		this.codeGroup = codeGroup;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.USE_YN
	 * @return  the value of PMS.CODE.USE_YN
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getUseYn() {
		return useYn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.USE_YN
	 * @param useYn  the value for PMS.CODE.USE_YN
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setUseYn(String useYn) {
		this.useYn = useYn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.SORT_ORDER
	 * @return  the value of PMS.CODE.SORT_ORDER
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.SORT_ORDER
	 * @param sortOrder  the value for PMS.CODE.SORT_ORDER
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.REGISTER_ID
	 * @return  the value of PMS.CODE.REGISTER_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getRegisterId() {
		return registerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.REGISTER_ID
	 * @param registerId  the value for PMS.CODE.REGISTER_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setRegisterId(String registerId) {
		this.registerId = registerId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.REGISTER_DATE
	 * @return  the value of PMS.CODE.REGISTER_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public Date getRegisterDate() {
		return registerDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.REGISTER_DATE
	 * @param registerDate  the value for PMS.CODE.REGISTER_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.UPDATE_ID
	 * @return  the value of PMS.CODE.UPDATE_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.UPDATE_ID
	 * @param updateId  the value for PMS.CODE.UPDATE_ID
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PMS.CODE.UPDATE_DATE
	 * @return  the value of PMS.CODE.UPDATE_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PMS.CODE.UPDATE_DATE
	 * @param updateDate  the value for PMS.CODE.UPDATE_DATE
	 * @ibatorgenerated  Fri Sep 13 15:52:15 KST 2013
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
}